title: Ultracycling races
description: >- # this means to ignore newlines until "baseurl:"
  List of ultracycling races
baseurl: "/ultracylcing-races"
url: "" # the base hostname & protocol for your site, e.g. http://example.com

sass:
  style: compressed
  sourcemap: development

# Build settings
theme: null
